from __future__ import annotations

ANALYTICS_WORKFLOW_BENCHMARK = "BENCHMARK"
ANALYTICS_WORKFLOW_BENCHMARK_EXPOSURE_CONTEXT = "BENCHMARK_EXPOSURE_CONTEXT"
ANALYTICS_WORKFLOW_MWR = "MWR"
ANALYTICS_WORKFLOW_TWR = "TWR"
ANALYTICS_WORKFLOW_TWR_INSPECTION = "TWR_INSPECTION"
ANALYTICS_WORKFLOW_WORKSPACE_SUMMARY = "WORKSPACE_SUMMARY"
