from __future__ import annotations

EXECUTION_STAGE_ARTIFACT_MATERIALIZATION = "artifact_materialization"
EXECUTION_STAGE_EXECUTION = "execution"
EXECUTION_STAGE_LINEAGE_MATERIALIZATION = "lineage_materialization"
EXECUTION_STAGE_MATH_RECONCILIATION = "math_reconciliation"
EXECUTION_STAGE_RETRIEVAL = "retrieval"
EXECUTION_STAGE_NORMALIZATION = "normalization"
EXECUTION_STAGE_SOURCE_ECONOMICS_ASSESSMENT = "source_economics_assessment"
EXECUTION_STAGE_SOURCE_QUALITY_ASSESSMENT = "source_quality_assessment"
EXECUTION_STAGE_SOURCE_STATE_RECONCILIATION = "source_state_reconciliation"
EXECUTION_STAGE_SUBMISSION = "submission"
EXECUTION_STAGE_SUBJECT_RESOLUTION = "subject_resolution"
EXECUTION_STAGE_FINDING_SYNTHESIS = "finding_synthesis"
