from app.core.config import Settings

VALID_PRODUCTION_RUNTIME_THRESHOLDS = {
    "RUNTIME_STATUS_COMPUTE_PENDING_AGE_DEGRADE_SECONDS": 600,
    "RUNTIME_STATUS_COMPUTE_LEASED_AGE_DEGRADE_SECONDS": 180,
    "RUNTIME_STATUS_COMPUTE_RUNNING_AGE_DEGRADE_SECONDS": 900,
    "RUNTIME_STATUS_COMPUTE_RETRY_BACKLOG_DEGRADE_COUNT": 3,
    "RUNTIME_STATUS_COMPUTE_LEASE_EXPIRY_DEGRADE_COUNT": 2,
    "RUNTIME_STATUS_COMPUTE_TERMINAL_FAILURE_DEGRADE_COUNT": 1,
    "RUNTIME_STATUS_LINEAGE_PENDING_AGE_DEGRADE_SECONDS": 600,
    "RUNTIME_STATUS_LINEAGE_LEASED_AGE_DEGRADE_SECONDS": 180,
    "RUNTIME_STATUS_LINEAGE_RETRY_BACKLOG_DEGRADE_COUNT": 3,
    "RUNTIME_STATUS_LINEAGE_TERMINAL_FAILURE_DEGRADE_COUNT": 1,
    "RUNTIME_STATUS_LINEAGE_STORAGE_MIN_FREE_BYTES": 5_368_709_120,
    "RUNTIME_STATUS_LINEAGE_STORAGE_MIN_FREE_RATIO": 0.2,
    "RUNTIME_STATUS_RECOVERY_DRILL_MAX_AGE_SECONDS": 259_200,
    "RUNTIME_STATUS_RECOVERY_DRILL_ACTIVE_RUN_AGE_DEGRADE_SECONDS": 3_600,
    "RUNTIME_STATUS_RECOVERY_DRILL_RECLAIM_DEGRADE_COUNT": 2,
    "RUNTIME_STATUS_RUNTIME_RETENTION_MAX_AGE_SECONDS": 259_200,
    "RUNTIME_STATUS_RUNTIME_RETENTION_ACTIVE_RUN_AGE_DEGRADE_SECONDS": 3_600,
    "RUNTIME_STATUS_RUNTIME_RETENTION_RECLAIM_DEGRADE_COUNT": 2,
}


def settings_with_runtime_thresholds(**overrides: object) -> Settings:
    return Settings(**(VALID_PRODUCTION_RUNTIME_THRESHOLDS | overrides))
