"""Curated reports must agree with the regenerated baseline they cite.

`quality/baseline_report.md` is regenerated by `make quality-baseline`.
`quality/refactor_health_report.md` and `quality/quality_scorecard.md` are curated by hand and both
restate figures from it - the scorecard names it as the source in its own source column.

A restated figure goes stale silently. Issue #475 drifted five times in one change: a flag value, a
prose value, a guard that read one sentence, a guard that read the wrong input set, and finally two
curated reports carrying a collected-test total the regenerated baseline contradicted. The taxonomy
guards could not see the last one, because both numbers are legitimate values of different things -
only their disagreement is the defect.

This closes that shape: any figure a curated report restates from the baseline must equal it, and
any delta derived from two stated figures must be their difference. The durable fix is to stop
copying - a row that says "see the regenerated report" cannot go stale - but while rows do copy,
they are checked.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BASELINE = ROOT / "quality" / "baseline_report.md"

# Accepts a leading sign, so a reduction is checked rather than skipped.
_SIGNED_INTEGER = re.compile(r"[+-]?\d+")

# Curated documents and the row label they restate from the baseline.
RESTATING_REPORTS = (
    ("quality/refactor_health_report.md", "Collected tests"),
    ("quality/quality_scorecard.md", "Collected tests"),
)


def _baseline_collected_tests() -> int:
    match = re.search(r"^\| Collected tests \| ([\d,]+) tests \|", BASELINE.read_text(encoding="utf-8"), re.M)
    assert match is not None, "The regenerated baseline no longer states a collected-test total."
    return int(match.group(1).replace(",", ""))


def _row_numbers(document: Path, label: str) -> list[int]:
    match = re.search(rf"^\| {re.escape(label)} \|(.+)$", document.read_text(encoding="utf-8"), re.M)
    assert match is not None, f"{document.name} no longer has a {label!r} row."
    return [
        int(cell.replace(",", "").strip())
        for cell in match.group(1).split("|")
        if cell.replace(",", "").strip().isdigit()
    ]


def test_curated_reports_agree_with_the_regenerated_baseline() -> None:
    measured = _baseline_collected_tests()

    disagreeing = []
    for relative_path, label in RESTATING_REPORTS:
        numbers = _row_numbers(ROOT / relative_path, label)
        assert numbers, f"{relative_path}: {label!r} row states no numbers."
        if measured not in numbers:
            disagreeing.append(f"{relative_path}: {label} states {numbers}, baseline says {measured}")

    assert disagreeing == [], (
        "These curated reports restate a figure from quality/baseline_report.md and disagree with "
        f"it. The scorecard cites that file as its source: {disagreeing}. See issue #475."
    )


def test_a_stated_delta_equals_the_difference_of_the_figures_beside_it() -> None:
    """`| metric | baseline | current | delta |` - the delta is derived, so it can be checked.

    The scorecard's collected-test delta read 1,771 against a stated 2,035 and 3,806, and stayed at
    1,771 when the current figure moved. A stale derived value is harder to spot than a stale stated
    one, because it looks like arithmetic somebody did.
    """

    scorecard = (ROOT / "quality" / "quality_scorecard.md").read_text(encoding="utf-8")

    wrong = []
    for row in re.findall(r"^\|([^|]+)\|([^|]+)\|([^|]+)\|([^|]+)\|", scorecard, re.M):
        label, baseline_cell, current_cell, delta_cell = (cell.strip() for cell in row)
        cells = [
            baseline_cell.replace(",", ""),
            current_cell.replace(",", ""),
            delta_cell.replace(",", ""),
        ]
        # `isdigit()` is false for "-100", so an earlier version silently skipped every row where
        # a metric had been *reduced* - which is precisely what a refactor scorecard exists to
        # track. A guard blind to the direction it cares about is not a guard.
        if not all(_SIGNED_INTEGER.fullmatch(cell) for cell in cells):
            continue
        baseline, current, delta = (int(cell) for cell in cells)
        if current - baseline != delta:
            wrong.append(f"{label}: {current} - {baseline} = {current - baseline}, stated {delta}")

    assert wrong == [], f"These scorecard deltas are not the difference of the figures beside them: {wrong}"


def test_a_negative_delta_is_checked_rather_than_skipped() -> None:
    """A reduction is exactly what a refactor scorecard tracks, so it must not be skipped.

    An earlier version gated on `cell.isdigit()`, which is false for "-100". Every row where a
    metric had been reduced was silently ignored - the guard was blind in the one direction the
    document exists to record.
    """

    assert _SIGNED_INTEGER.fullmatch("-100") is not None
    assert _SIGNED_INTEGER.fullmatch("+12") is not None
    assert _SIGNED_INTEGER.fullmatch("3861") is not None
    assert _SIGNED_INTEGER.fullmatch("n/a") is None
    assert _SIGNED_INTEGER.fullmatch("") is None
    assert not "-100".isdigit()  # the reason the earlier form skipped it


def test_the_generated_inventory_explains_that_family_counts_overlap() -> None:
    """The caveat must be emitted by the generator, not carried by the curated file.

    It lived in the document, and a mechanical regeneration of that block deleted it - leaving a
    family table whose values sum to more than the stated total with no explanation, which reads as
    an internally inconsistent report. Generated output has to carry its own caveats, because the
    thing that rewrites it does not know they were there.
    """

    import subprocess
    import sys

    completed = subprocess.run(
        [sys.executable, "scripts/python_test_taxonomy_inventory.py", "--limit", "5"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert completed.returncode == 0, completed.stderr
    assert "overlap by design and do not sum to the total" in completed.stdout

    published = (ROOT / "quality" / "test_taxonomy_inventory.md").read_text(encoding="utf-8")
    assert "overlap by design and do not sum to the total" in published
